### ISSUE TITLE
Command is invalid when running test prepare command through Azure DevOps task

### ISSUE THREAD

**Issue by rygo-msft** [microsoft/appcenter-cli#696]
Starting last week (11/7 4:00 AM EST) our AppCenterTest runs have been failing to submit from Azure DevOps.

When running in the vs2017-win2016 hosted agent image using the AppCenterTest task, the prepare step has begun failing. It does not appear to be an issue with the task as the command sent to the CLI is identical to what successful jobs were sending.

```
- task: AppCenterTest@1
  name: RunAppCenterTests
  displayName: 'Test with Visual Studio App Center'
  inputs:
    espressoBuildDirectory: ${{ parameters.appBuildDir }}
    appFile: ${{ parameters.appFile }}
    artifactsDirectory: AppCenterTest
    frameworkOption: espresso
    serverEndpoint: 9015e276-e51e-4284-bcf0-6b56a5517017 #MAM functional test connection
    appSlug: ${{ parameters.appCenterAppId }}
    devices: $(DeviceSelector.Devices)
    runOptions: ${{ parameters.runOptions }}
```

```
C:\windows\system32\cmd.exe /D /S /C "D:\a\_tasks\AppCenterTest_ad5cd22a-be4e-48bb-adce-181a32432da5\1.152.1\node_modules\.bin\appcenter.cmd test prepare espresso --artifacts-dir D:\a\1\s\AppCenterTest --build-dir D:\a\1\a\MAM\AppClient.Test.Functional --quiet"
Error: Command test prepare espresso --artifacts-dir D:\a\1\s\AppCenterTest --build-dir D:\a\1\a\MAM\AppClient.Test.Functional --quiet is invalid
```
